### ISSUE TITLE
Inconsistent zombie rage visual clues

### ISSUE THREAD

**Issue by RenaudF** [pardeike/Zombieland#10]
- zombies sometimes show brainzz mote without raging, assuming that's when that mote is supposed to mean...
 - zombies sometimes run without raging, i.e showing brainz mote or glowing red
 - zombies sometimes rage (glow red) without running

tested without other mods

**Comment by pardeike** [comment]
Not exactly. There are two motes:

1) Brain mote
This is thrown when a zombie detects a “trace” of an enemy. Think of it as a combination of sound and smell. It’s like sound because it is emitted when you shoot or walk and it is like smell as it stays on a cell until it fades away. Zombies use it to follow you. That mote is thrown when a zombie goes from “wandering” to “tracking”. Tracking is less intelligent than raging because it only works with short to medium ranges and depends on traces not faded away.

2) Angry face mote
This is thrown when a zombie is stressed by too many other zombies close by. It will go into “raging” mode. That mode persists for a certain time or until certain other conditions that I don’t go into here now. Raging is more intelligent than tracking because it has elements of real pathing.

**Comment by RenaudF** [comment]
That makes sense, though I'm not sure if a brain is the best choice for representing the underlying mechanism. I don't remember seeing an angry face mote, though I could have just missed it, but I can hear zombies when they start raging so that's good. I have seen the food mote when zombies start munching on a corpse/downed pawn.

I would still expect glowing zombies to be running and conversely, not glowing zombies to go slow but I have seen instances of glowing zombies walking and non glowing zombies running.

**Comment by pardeike** [comment]
No fix. Current behavior works well enough.
