### ISSUE TITLE
love it! but...

### ISSUE THREAD

**Issue by eksynn** [pardeike/Zombieland#18]
i love your mod!
just one thing i'm wondering about: why can i not loot them? i understand them rotting away quickly, even though i think it's _way too quickly_ xD;

i understand the technical reason for this though - lag
if there are too many corpses and too many loose items, the game lags. but is there no way to add the option to make them lootable, and/or to make their bodies stay longer?

**Comment by pardeike** [comment]
Would be way OP bc they would give you an endless supply

**Comment by eksynn** [comment]
> Would be way OP bc they would give you an endless supply

i mean, they don't have to always have loot on them - there could be only a tiny chance of any loot being present in their inventories... could also be default OFF so people have to actually turn it on, if they like it xD

and what about making the bodies stay longer? (also as a setting)

edit: aah closed it so quickly without answering _both_ questions D;

**Comment by pardeike** [comment]
Which would require me to enable:
- that you can select them
- the pawn selector

Selecting them when you have 500 or more of them will make selecting other things very difficult. 

Selecting them and having the inspector show would require them to have all the normal properties a human pawn has. Which they don’t because I patched away most unused properties like inventory, mood, specific health details, background story, ageing, event log.

I could re-add that but it would make them much slower and consume a lot of memory. 

To solve that, I would need to reduce the number of zombies substantially which would require me to make them smarter because a few dumb zombies stuck somewhere isn’t really appealing. Which would require me to make them intelligent like raiders. Basically reverting most zombie like behaviour that makes them unique. At that point, you could simply take any race mod and add a few zombie graphics to it and your done.

Doesn’t sound very appealing to me.

**Comment by eksynn** [comment]
> Selecting them when you have 500 or more of them will make selecting other things very difficult.

i mean, they vanish quickly enough xD plus there's a drop-down menu I could re-add that but it would

> make them much slower and consume a lot of memory.when you right-click things

oh... so back to the "technical issues" thing -- would this happen even optionally? (so you can turn that on and off via mod settings)

**Comment by pardeike** [comment]
At this point, a mod that is already very complex and allows for many configurable things becomes very difficult to maintain as I have to adapt half the code base to those changes that look like “just add an option” on the surface. After more than 1500 hours of coding, if I would simply add stuff people suggest, it would become this huge mess that does nothing perfect but only consist of features that some people like and others don’t. 

Sorry, but after 35 years of professional software development I know that without a clean vision for a product, you end up with this incoherent mess. A good product requires to make sacrifices and a good vision will limit the number of features. 

One of the principles I decided on early is to make zombies not like other pawns on the map. I suggest you use the other zombie mod. It even has zombie animals.
