### ISSUE TITLE
Zombies don't spawn

### ISSUE THREAD

**Issue by minimar** [pardeike/Zombieland#25]
Zombies are set to spawn at all times from edge of the map, with days until set to 0. No zombies spawn.

Tried changing to soft ground, tried changing to only at nighttime, no effect. Using Zombieland 2.0.1.1 With RimWorld 1.1.2552 64-bit, no additional mods.

Zombies can be successfully spawned using dev mode.

**Comment by pardeike** [comment]
Try the latest release. If it does not work, please use dev mode and look at the inspector panel (the spyglas button) and post a screenshot of it.

**Comment by minimar** [comment]
[Still having issues, unfortunatenly](https://i.imgur.com/GEGdKUo.png)

If it helps, testing is being done using the regular Crashlanded scenario.

I noticed "too few capable colonists" and decided to experiment by spawning a ton of colonists using dev mode, nothing changed.

**Comment by pardeike** [comment]
Colonists without weapons don’t count. So does any colonist that cannot fight zombies for some reason (mental break etc).

**Comment by minimar** [comment]
After equipping weapons, zombies spawn correctly. Closed! However, it is a very odd start to the game that zombies don't even spawn until you have a weapon. Is this documented? It definitely should be, if not.

**Comment by pardeike** [comment]
Zombieland has lots of surprises. I find it boring to reveal all things I build in. It’s like spoilers to a movie. Instead try to discover the mod - it adds to replayability and a more interesting play style. 

In this particular case it is actually good that if you choose to stay without weapons you won’t get zombies but playing RimWorld will ultimately force you to use weapons and that leads to probably unexpected situations so that each game is different from the previous. Different play styles make Zombieland surprisingly different.
