### ISSUE TITLE
[feature request] Option to make zombies leave during day

### ISSUE THREAD

**Issue by mc-oofy** [pardeike/Zombieland#26]
the title actually explains it all
when the setting is on zombies leave when its day

**Comment by pardeike** [comment]
So what do you mean by leave? Can you explain in more detail what should happen to them? Those at the corners of the map, those in the center of a large map. What happens to those enclosed by walls or other obstacles? And those that are busy with feeding or chasing or the slow tanks going for your walls? Do you think they will have enough time to actually leave the map during the night?

**Comment by mc-oofy** [comment]
those stuck will try to get out by attacking the walls/blocking object
and those not stuck will just walk like normal fleeing raiders
and those who wont have enough time could
a) just find a dark spot to rest at if the appear at dark option is enabled or just find a spot to lie on
b)keep trying to get out of the map
c)die from sunburn when the appear at dark option is enabled i guess

**Comment by pardeike** [comment]
Unfortunately zombies don’t scan the map for objects because that would slow down your game to a crawl. So all those options sound nice but are very impractical unless you like 3fps. The whole code of Zombieland is all about making zombies NOT behave like intelligent enemies and the mod strips away basically all game functions from them to archive the game play I want: playing with large hordes of zombies acting like a flock. 

I also see lots of edge cases with your suggestions. Maybe you should suggest it to the other guy doing a more standard approach - that mod is called Zombified.

**Comment by mc-oofy** [comment]
k thanks anyways
