### ISSUE TITLE
Exception in Verse.AI.ThinkNode_Priority.TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by janaxis** [pardeike/Zombieland#52]
Hi,
I keep getting an error when pawns attack zombies. Not sure if issue is with MVCF or Zombieland.
Issue posted to both =)

Zombieland is last in modlist.

hugslib log: https://gist.github.com/HugsLibRecordKeeper/d8c77bf1d62c6bab1b142a08da7d2f48

![error](https://user-images.githubusercontent.com/94777181/181393477-40dff8ed-491c-453b-983f-99da7726df59.PNG)
[error.txt](https://github.com/pardeike/Zombieland/files/9204303/error.txt)

**Comment by pardeike** [comment]
The topmost section of the exception is the troublemaker. I would suggest to report to them. 

This vanilla function has a NRE:

`Verse.GridsUtility.GetRoof (Verse.IntVec3 c, Verse.Map map)`

called by

`DarknessCombatUtility.Outdoors (Verse.Thing thing)`

called by

`DarknessCombatUtility.IsOutdoorsAndLit (Verse.Thing thing)`

**Comment by pardeike** [comment]
TIL that these methods are part of Vanilla. So let me re-evaluate the problem. The topmost patch in that stacktrace is
`ShotReport.HitReportFor: PRE: VFECore.Patch_Verb+ShotReport_HitReportFor.Prefix`
So I would start looking at that mod or any interactions that it might have.

For now I am closing this because I am pretty confident that it's not a Zombieland problem.
